spring:
  datasource:
    url: jdbc:mysql://***.***.***.***:**/CloudStudy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ***
    password: *********
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: "Asia/Shanghai"

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8088
